# Generated by Django 5.1.5 on 2025-03-09 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_userchapterprogress_userquestionanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquestionanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userquestionanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestionanswer',
            name='user',
        ),
        migrations.CreateModel(
            name='ModelTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correct', models.PositiveIntegerField()),
                ('wrong', models.PositiveIntegerField()),
                ('unattempted', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='UserChapterProgress',
        ),
        migrations.DeleteModel(
            name='UserQuestionAnswer',
        ),
    ]
